package webmaster

// CommonRegions is a curated shortlist for query-analytics region_ids.
// Yandex has thousands of regions; this is not a complete catalog.
var CommonRegions = []Region{
	{ID: 225, Name: "Russia"},
	{ID: 213, Name: "Moscow"},
	{ID: 2, Name: "Saint Petersburg"},
	{ID: 1, Name: "Moscow and Moscow Oblast"},
	{ID: 10174, Name: "Saint Petersburg and Leningrad Oblast"},
	{ID: 65, Name: "Novosibirsk"},
	{ID: 54, Name: "Yekaterinburg"},
	{ID: 47, Name: "Nizhny Novgorod"},
	{ID: 43, Name: "Kazan"},
	{ID: 56, Name: "Chelyabinsk"},
	{ID: 51, Name: "Samara"},
	{ID: 66, Name: "Omsk"},
	{ID: 39, Name: "Rostov-on-Don"},
	{ID: 172, Name: "Ufa"},
	{ID: 35, Name: "Krasnodar"},
	{ID: 62, Name: "Krasnoyarsk"},
	{ID: 193, Name: "Voronezh"},
	{ID: 63, Name: "Volgograd"},
	{ID: 187, Name: "Ukraine"},
	{ID: 143, Name: "Kyiv"},
	{ID: 149, Name: "Belarus"},
	{ID: 157, Name: "Minsk"},
	{ID: 159, Name: "Kazakhstan"},
	{ID: 162, Name: "Almaty"},
	{ID: 10393, Name: "Nur-Sultan (Astana)"},
	{ID: 983, Name: "Uzbekistan"},
	{ID: 10295, Name: "Armenia"},
	{ID: 10277, Name: "Azerbaijan"},
	{ID: 20544, Name: "Georgia"},
	{ID: 207, Name: "Kyrgyzstan"},
}

// FeedRegions lists regions accepted by YML feed uploads.
// There is no API endpoint for this list; it follows the Webmaster documentation.
var FeedRegions = []Region{
	{ID: 225, Name: "Россия (default)"},
	{ID: 20, Name: "Архангельск"},
	{ID: 37, Name: "Астрахань"},
	{ID: 197, Name: "Барнаул"},
	{ID: 4, Name: "Белгород"},
	{ID: 77, Name: "Благовещенск"},
	{ID: 191, Name: "Брянск"},
	{ID: 24, Name: "Великий Новгород"},
	{ID: 75, Name: "Владивосток"},
	{ID: 33, Name: "Владикавказ"},
	{ID: 192, Name: "Владимир"},
	{ID: 38, Name: "Волгоград"},
	{ID: 21, Name: "Вологда"},
	{ID: 193, Name: "Воронеж"},
	{ID: 1106, Name: "Грозный"},
	{ID: 54, Name: "Екатеринбург"},
	{ID: 5, Name: "Иваново"},
	{ID: 63, Name: "Иркутск"},
	{ID: 41, Name: "Йошкар-Ола"},
	{ID: 43, Name: "Казань"},
	{ID: 22, Name: "Калининград"},
	{ID: 64, Name: "Кемерово"},
	{ID: 7, Name: "Кострома"},
	{ID: 35, Name: "Краснодар"},
	{ID: 62, Name: "Красноярск"},
	{ID: 53, Name: "Курган"},
	{ID: 8, Name: "Курск"},
	{ID: 9, Name: "Липецк"},
	{ID: 28, Name: "Махачкала"},
	{ID: 1, Name: "Москва и Московская область"},
	{ID: 213, Name: "Москва"},
	{ID: 1092, Name: "Назрань"},
	{ID: 30, Name: "Нальчик"},
	{ID: 47, Name: "Нижний Новгород"},
	{ID: 65, Name: "Новосибирск"},
	{ID: 66, Name: "Омск"},
	{ID: 10, Name: "Орел"},
	{ID: 48, Name: "Оренбург"},
	{ID: 49, Name: "Пенза"},
	{ID: 50, Name: "Пермь"},
	{ID: 25, Name: "Псков"},
	{ID: 39, Name: "Ростов-на-Дону"},
	{ID: 11, Name: "Рязань"},
	{ID: 51, Name: "Самара"},
	{ID: 2, Name: "Санкт-Петербург"},
	{ID: 42, Name: "Саранск"},
	{ID: 12, Name: "Смоленск"},
	{ID: 239, Name: "Сочи"},
	{ID: 36, Name: "Ставрополь"},
	{ID: 973, Name: "Сургут"},
	{ID: 13, Name: "Тамбов"},
	{ID: 14, Name: "Тверь"},
	{ID: 67, Name: "Томск"},
	{ID: 15, Name: "Тула"},
	{ID: 195, Name: "Ульяновск"},
	{ID: 172, Name: "Уфа"},
	{ID: 76, Name: "Хабаровск"},
	{ID: 45, Name: "Чебоксары"},
	{ID: 56, Name: "Челябинск"},
	{ID: 1104, Name: "Черкесск"},
	{ID: 16, Name: "Ярославль"},
}
